spring.application.name=portfolio

# URL към базата данни (порт 5432 е стандартният за Postgres)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portfolio_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:run}

# Хибернейт конфигурация (автоматично ще създава таблиците в базата на база Java кода ни)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

